name: Fetch Star Projects

on:
  schedule:
    - cron: '0 0 * * 0'  # 每天运行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch-star-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # 使用你设置的 secret
          
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run fetch script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bun run sync
        
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: fetch star projects [skip ci]" || exit 0
          git push
